# Generated by Django 2.2.7 on 2019-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='nutritions',
            field=models.ManyToManyField(to='goods.Good'),
        ),
    ]
