# Generated by Django 2.2.7 on 2019-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('type_0f_nutrition', models.CharField(choices=[('PROTEIN', 'protein'), ('CREATINE', 'creatine'), ('BCAA', 'BCAA'), ('FATBURNS', 'FatBURNS'), ('GEINER', 'GEINER')], default='PROTEIN', max_length=20)),
                ('avaiable', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('company', models.ManyToManyField(to='company.Companys')),
            ],
        ),
    ]
