# Generated by Django 2.2.7 on 2019-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
