# Generated by Django 2.2.7 on 2019-12-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_companys_nutritions'),
        ('goods', '0002_good_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='company',
        ),
        migrations.AddField(
            model_name='good',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Companys'),
        ),
    ]
